# Generated by Django 5.2 on 2025-04-17 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planet',
            name='climates',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='planet',
            name='population',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planet',
            name='terrains',
            field=models.CharField(max_length=255),
        ),
    ]
