# Generated by Django 5.2 on 2025-04-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planets', '0002_alter_planet_climates_alter_planet_population_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planet',
            name='climates',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='planet',
            name='terrains',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
